from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session
from db.database import get_db
from agents.chat_agent import ChatAgent

router = APIRouter(tags=["Q&A Chatbot"])
chat_agent = ChatAgent()

class ChatRequest(BaseModel):
    document_id: str = Field(..., description="UUID of the uploaded document")
    question: str = Field(..., description="The question asked by the student")
    model_name: str | None = Field(None, description="Optional model choice")

@router.post("/ask", status_code=status.HTTP_200_OK)
def ask_question(
    request: ChatRequest,
    db: Session = Depends(get_db)
):
    """
    Accepts a question and document ID, retrieves relevant chunks from vector store,
    and returns a grounded answer generated by the Gemini API.
    """
    try:
        result = chat_agent.ask_question(
            db=db,
            document_id=request.document_id,
            question=request.question,
            model_name=request.model_name
        )
        return result
    except ValueError as ve:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=str(ve)
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Chat generation failed: {str(e)}"
        )
